In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [19]:
import pandas as pd
import numpy as np
import re

In [3]:
notice_details_original = pd.read_csv("../../datos_navent_fiuba/fiuba_6_avisos_detalle.csv")
notice_details_from_15 = pd.read_csv("../../fiuba_6_avisos_detalle.csv")
notice_details_from_15_missing = pd.read_csv("../../fiuba_6_avisos_detalle_missing_nivel_laboral.csv")
notice_details_to_15 = pd.read_csv("../../entrega6/fiuba_6_avisos_detalle.csv")

### Veo como son los datos y la longitud de los csv

In [4]:
notice_details_original.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,8725750,1,VENDEDOR/A PROVINCIA DE SANTA FE,<p><strong><strong>Empresa:</strong></strong> ...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Comercial,VENTOR
1,17903700,1,Enfermeras,<p>Solicitamos para importante cadena de farma...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Salud,Farmacias Central Oeste
2,1000150677,1,Chofer de taxi,<p>TE GUSTA MANEJAR? QUERES GANAR PLATA HACIEN...,Capital Federal,NaN,Empedrado 2336,Full-time,Senior / Semi-Senior,Transporte,FAMITAX SRL
3,1000610287,1,CHOFER DE CAMIONETA BAHIA BLANCA - PUNTA ALTA,<p><strong>Somos una empresa multinacional que...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Transporte,Wurth Argentina S.A
4,1000872556,1,Operarios de Planta - Rubro Electrodomésticos,<p><strong>OPERARIOS DE PLANTA</strong></p><p>...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Producción,ELECTRO OUTLET SRL

In [5]:
print(len(notice_details_original))

13534

In [6]:
notice_details_from_15.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1573840,1,VENDEDORA/O,Nuestra Búsqueda se orienta a la incorporación...,Capital Federal,Flores,NaN,Full-time,Otro,Ventas,RIBEIRO SUC. FLORES
1,1712970,1,INGENIERO DE PRODUCTO,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,Capital Federal,NaN,NaN,Full-time,Otro,Otras Ingenierias,Aparatos Electricos Automaticos SA
2,1719970,1,** Diseñadores/as Gráficos Quark Express **,Diseñadores/as Gráficos Quark Express para Rev...,Capital Federal,NaN,NaN,Full-time,Otro,Diseño,Revista NEX IT Specialist ? Editorial Poulbert
3,1720060,1,Soporte Tecnico,Estudiante de Sistemas (Lic. en Sistemas de la...,Capital Federal,NaN,NaN,Full-time,Otro,Tecnologia / Sistemas,Tango Software
4,1720280,1,ADSCRIPTO DE GERENCIA,Importante Organización Académica Empresarial\...,Buenos Aires (fuera de GBA),NaN,NaN,Full-time,Otro,Otros,Experis

In [7]:
print(len(notice_details_from_15))

13798

In [8]:
notice_details_from_15_missing.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1001284385,1,Dejanos tu CV,<p><br />Si est&aacute;s interesado en ser par...,Corrientes,NaN,NaN,Full-time,NaN,Otros,Establecimiento Las Marías
1,1110092955,1,para línea de producción (ref. 28376),<p>Empresas vinculadas a la industria automotr...,GBA Oeste,NaN,NaN,Full-time,NaN,Producción,RANDSTAD
2,1110092958,1,para mantenimiento (ref. 27181),"<p style=""display: inline !important;"">Empresa...",GBA Oeste,NaN,NaN,Full-time,NaN,Mantenimiento,RANDSTAD
3,1110391074,1,Trabajá con nosotros,<p><strong>Trabaj&aacute; con nosotros</strong...,Cordoba,NaN,NaN,Full-time,NaN,Ingeniería Industrial,Coca Cola Andina Argentina
4,1110669632,1,Técnico de Mantenimiento,<p>Experiencia en f&aacute;bricas cosm&eacute;...,GBA Oeste,NaN,", Lanús",Full-time,NaN,Mantenimiento,PLUMARI S A

In [9]:
print(len(notice_details_from_15_missing))

338

In [10]:
notice_details_to_15.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1111556097,1,Responsable de Marketing-Producto Div. Constru...,<p>Buscamos un <strong>Responsable de Producto...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Desarrollo de Negocios,Sinteplast S.A.
1,1111949392,1,Asesor de Servicios - Postventa Chevrolet,"<p><span style="""">Para nuestro cliente, conces...",Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Ingeniería Eléctrica y Electrónica,Roycan
2,1112145935,1,Analistas de Impuestos Sr Ssr y Jr,<p>Importante Estudio de Auditoria y Consultor...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Impuestos,Lighthouse Smart
3,1112146010,1,Software Engineer,<p> </p><p>Chevron is a multinational company ...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Programación,Chevron Buenos Aires Shared Services Center
4,1112211475,1,Business Developer Manager,"<p>Importante empresa de energías renovables, ...",Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Comercial,RANDSTAD

In [11]:
print(len(notice_details_to_15))

18299

### Mergeo 2 conjuntos de csv

In [12]:
notice_aux_1 = pd.merge(notice_details_from_15, notice_details_from_15_missing, on = None, how = 'outer')
notice_aux_2 = pd.merge(notice_details_original, notice_details_to_15, on = None, how = 'outer')

In [13]:
notice_aux_1.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1573840,1,VENDEDORA/O,Nuestra Búsqueda se orienta a la incorporación...,Capital Federal,Flores,NaN,Full-time,Otro,Ventas,RIBEIRO SUC. FLORES
1,1712970,1,INGENIERO DE PRODUCTO,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,Capital Federal,NaN,NaN,Full-time,Otro,Otras Ingenierias,Aparatos Electricos Automaticos SA
2,1719970,1,** Diseñadores/as Gráficos Quark Express **,Diseñadores/as Gráficos Quark Express para Rev...,Capital Federal,NaN,NaN,Full-time,Otro,Diseño,Revista NEX IT Specialist ? Editorial Poulbert
3,1720060,1,Soporte Tecnico,Estudiante de Sistemas (Lic. en Sistemas de la...,Capital Federal,NaN,NaN,Full-time,Otro,Tecnologia / Sistemas,Tango Software
4,1720280,1,ADSCRIPTO DE GERENCIA,Importante Organización Académica Empresarial\...,Buenos Aires (fuera de GBA),NaN,NaN,Full-time,Otro,Otros,Experis

In [14]:
print(len(notice_aux_1))

14136

In [15]:
notice_aux_2.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,8725750,1,VENDEDOR/A PROVINCIA DE SANTA FE,<p><strong><strong>Empresa:</strong></strong> ...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Comercial,VENTOR
1,17903700,1,Enfermeras,<p>Solicitamos para importante cadena de farma...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Salud,Farmacias Central Oeste
2,1000150677,1,Chofer de taxi,<p>TE GUSTA MANEJAR? QUERES GANAR PLATA HACIEN...,Capital Federal,NaN,Empedrado 2336,Full-time,Senior / Semi-Senior,Transporte,FAMITAX SRL
3,1000610287,1,CHOFER DE CAMIONETA BAHIA BLANCA - PUNTA ALTA,<p><strong>Somos una empresa multinacional que...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Transporte,Wurth Argentina S.A
4,1000872556,1,Operarios de Planta - Rubro Electrodomésticos,<p><strong>OPERARIOS DE PLANTA</strong></p><p>...,Gran Buenos Aires,NaN,NaN,Full-time,Senior / Semi-Senior,Producción,ELECTRO OUTLET SRL

In [16]:
print(len(notice_aux_2))

19685

### Mergeo los dos conjuntos de csv

In [17]:
notice_details = pd.merge(notice_aux_1, notice_aux_2, on = None, how = 'outer')
notice_details.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1573840,1,VENDEDORA/O,Nuestra Búsqueda se orienta a la incorporación...,Capital Federal,Flores,NaN,Full-time,Otro,Ventas,RIBEIRO SUC. FLORES
1,1712970,1,INGENIERO DE PRODUCTO,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,Capital Federal,NaN,NaN,Full-time,Otro,Otras Ingenierias,Aparatos Electricos Automaticos SA
2,1719970,1,** Diseñadores/as Gráficos Quark Express **,Diseñadores/as Gráficos Quark Express para Rev...,Capital Federal,NaN,NaN,Full-time,Otro,Diseño,Revista NEX IT Specialist ? Editorial Poulbert
3,1720060,1,Soporte Tecnico,Estudiante de Sistemas (Lic. en Sistemas de la...,Capital Federal,NaN,NaN,Full-time,Otro,Tecnologia / Sistemas,Tango Software
4,1720280,1,ADSCRIPTO DE GERENCIA,Importante Organización Académica Empresarial\...,Buenos Aires (fuera de GBA),NaN,NaN,Full-time,Otro,Otros,Experis

In [18]:
print(len(notice_details))

25901

### Hago una limpieza de la descripción, eliminando el código HTML

In [20]:
cleanr = re.compile('<.*?>')
def cleanhtml(raw_html):
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

In [21]:
notice_details["descripcion"] = notice_details["descripcion"].apply(lambda x: cleanhtml(x))

### Chequeamos las descripciones

In [22]:
notice_details.head()

,idaviso,idpais,titulo,descripcion,nombre_zona,ciudad,mapacalle,tipo_de_trabajo,nivel_laboral,nombre_area,denominacion_empresa
0,1573840,1,VENDEDORA/O,Nuestra Búsqueda se orienta a la incorporación...,Capital Federal,Flores,NaN,Full-time,Otro,Ventas,RIBEIRO SUC. FLORES
1,1712970,1,INGENIERO DE PRODUCTO,INGENIERO ELECTRICISTA/ELECTRONICO CON CONOCIM...,Capital Federal,NaN,NaN,Full-time,Otro,Otras Ingenierias,Aparatos Electricos Automaticos SA
2,1719970,1,** Diseñadores/as Gráficos Quark Express **,Diseñadores/as Gráficos Quark Express para Rev...,Capital Federal,NaN,NaN,Full-time,Otro,Diseño,Revista NEX IT Specialist ? Editorial Poulbert
3,1720060,1,Soporte Tecnico,Estudiante de Sistemas (Lic. en Sistemas de la...,Capital Federal,NaN,NaN,Full-time,Otro,Tecnologia / Sistemas,Tango Software
4,1720280,1,ADSCRIPTO DE GERENCIA,Importante Organización Académica Empresarial\...,Buenos Aires (fuera de GBA),NaN,NaN,Full-time,Otro,Otros,Experis

In [24]:
print(len(notice_details))

25901

### Lo guardo en un CSV limpio

In [23]:
notice_details.to_csv("../csvs/fiuba_6_avisos_detalle.csv", index=False)