In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
# Load libraries
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [3]:
post_info = pd.read_csv('csvs/postulantes_informacion.csv')
test_full = pd.read_csv('csvs/test_full.csv')

In [4]:
post_info.head()

,idpostulante,nombre,estado,nivel,sexo,edad,idaviso,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area
0,NdJl,6,1,7,MASC,49,1112261212,Gran Buenos Aires,Full-time,Jefe / Supervisor / Responsable,Administración
1,NdJl,4,2,6,MASC,49,1112261212,Gran Buenos Aires,Full-time,Jefe / Supervisor / Responsable,Administración
2,EppJmb,4,1,5,MASC,58,1112261212,Gran Buenos Aires,Full-time,Jefe / Supervisor / Responsable,Administración
3,EppJmb,4,2,6,MASC,58,1112261212,Gran Buenos Aires,Full-time,Jefe / Supervisor / Responsable,Administración
4,8Zr1GD,3,1,4,MASC,42,1112261212,Gran Buenos Aires,Full-time,Jefe / Supervisor / Responsable,Administración

In [5]:
post_info.shape

(10641324, 11)

In [6]:
test_full.head()

,Unnamed: 0,idaviso,idpostulante,nombre,estado,nivel,sexo,edad,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area
0,0,739260,6M9ZQR,7.0,2.0,9.0,FEM,42.0,Capital Federal,Full-time,Jefe / Supervisor / Responsable,Comercial
1,1,739260,6v1xdL,3.0,2.0,5.0,MASC,31.0,Capital Federal,Full-time,Jefe / Supervisor / Responsable,Comercial
2,2,739260,ezRKm9,4.0,2.0,6.0,FEM,36.0,Capital Federal,Full-time,Jefe / Supervisor / Responsable,Comercial
3,3,758580,1Q35ej,6.0,2.0,8.0,MASC,68.0,Capital Federal,Full-time,Otro,Tecnologia / Sistemas
4,4,758580,EAN4J6,4.0,1.0,5.0,FEM,32.0,Capital Federal,Full-time,Otro,Tecnologia / Sistemas

In [7]:
test_full.shape

(100000, 12)

In [8]:
test_full.drop('Unnamed: 0', 1, inplace = True)

In [9]:
df_concat = pd.concat([test_full, post_info], ignore_index = True)

In [10]:
df_concat.shape

(10741324, 11)

In [11]:
df_concat['sexo'].value_counts()

FEM     5725963
MASC    5008663
Name: sexo, dtype: int64

In [12]:
df_concat['nombre_zona'].value_counts()

Gran Buenos Aires              9749297
Capital Federal                 963115
Buenos Aires (fuera de GBA)      10519
GBA Oeste                         9286
Cordoba                           7805
Corrientes                        1240
La Plata                            13
Ciudad de Mendoza                   11
Mendoza                              9
Rosario                              7
San Juan                             4
Santa Fe                             4
Tucuman                              4
Santa Cruz                           4
Neuquen                              3
Catamarca                            3
Name: nombre_zona, dtype: int64

In [13]:
df_concat['tipo_de_trabajo'].value_counts()

Full-time          9084466
Part-time          1492164
Pasantia             54630
Temporario           32169
Por Horas            31589
Por Contrato         16490
Fines de Semana      13534
Teletrabajo          12740
Primer empleo         3169
Voluntario             373
Name: tipo_de_trabajo, dtype: int64

In [14]:
df_concat['nivel_laboral'].value_counts()

Senior / Semi-Senior                    6792976
Junior                                  2441760
Otro                                     836195
Jefe / Supervisor / Responsable          335838
Gerencia / Alta Gerencia / Dirección      85688
Name: nivel_laboral, dtype: int64

In [15]:
df_concat['nombre_area'].value_counts()

Ventas                                       1438343
Administración                               1084438
Comercial                                     783484
Atención al Cliente                           694997
Producción                                    673786
Recepcionista                                 551914
Call Center                                   453625
Telemarketing                                 281155
Tesorería                                     279789
Contabilidad                                  211476
Recursos Humanos                              187363
Almacén / Depósito / Expedición               164919
Mantenimiento y Limpieza                      153991
Secretaria                                    147470
Logística                                     142164
Marketing                                     137042
Gastronomia                                   130355
Administración de Personal                    123851
Créditos y Cobranzas                          117833
Legal                                         107105
Soporte Técnico                               104780
Finanzas                                       97322
Compras                                        93217
Farmacéutica                                   82003
Mantenimiento                                  77168
Camareros                                      76897
Selección                                      75587
Seguridad                                      73235
Jóvenes Profesionales                          73101
Oficios y Profesiones                          64231
                                              ...
Mercadotecnia Internacional                      507
Auditoría Médica                                 477
Arte y Cultura                                   447
Diseño 3D                                        434
Instrumentación Minera                           416
Responsabilidad Social                           415
Exploración Minera y Petroquimica                405
Idiomas                                          376
Trabajo social                                   365
Ingeniería Geológica                             228
Instrumentación quirúrgica                       210
Trabajo Social                                   202
Educación especial                               174
Emergentología                                   159
Cuidados Intensivos Cardiologicos Adultos        131
Topografía                                        89
Kinesiología / terapia ocupacional                69
Clínica Médica                                    60
Diagnóstico por imágenes                          57
Prácticas cardiológicas                           28
Urbanismo                                         27
Farmacia hospitalaria                             27
Esterilización                                    25
Psicología                                        23
Maternidad                                        13
Traduccion                                         8
Enfermería (ver Enfermería)                        6
Odontología                                        6
Fonoaudiología                                     5
Auditoría de Seguros                               3
Name: nombre_area, Length: 188, dtype: int64

In [16]:
df_concat = pd.get_dummies(df_concat, columns=['nombre_zona', 'tipo_de_trabajo', 'nivel_laboral'])

#test_full.drop(['idpostulante', 'idaviso'], 1, inplace = True)
#post_info.drop(['idpostulante', 'idaviso'], 1, inplace = True)
#df_concat.drop(['idpostulante', 'idaviso'], 1, inplace = True)
le = preprocessing.LabelEncoder()
for col in df_concat.columns:
    if not df_concat[col].dtype == 'O': continue
    print(col)
    le.fit(df_concat[col])
    df_concat[col] = le.transform(df_concat[col])
df_concat.head()

In [17]:
df_concat['sexo'] = df_concat['sexo'].astype('category').cat.codes
df_concat['nombre_area'] = df_concat['nombre_area'].astype('category').cat.codes

In [18]:
df_concat.head(10)

,edad,estado,idaviso,idpostulante,nivel,nombre,nombre_area,sexo,nombre_zona_Buenos Aires (fuera de GBA),nombre_zona_Capital Federal,...,tipo_de_trabajo_Por Horas,tipo_de_trabajo_Primer empleo,tipo_de_trabajo_Teletrabajo,tipo_de_trabajo_Temporario,tipo_de_trabajo_Voluntario,nivel_laboral_Gerencia / Alta Gerencia / Dirección,nivel_laboral_Jefe / Supervisor / Responsable,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior
0,42.0,2.0,739260,6M9ZQR,9.0,7.0,30,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,31.0,2.0,739260,6v1xdL,5.0,3.0,30,1,0,1,...,0,0,0,0,0,0,1,0,0,0
2,36.0,2.0,739260,ezRKm9,6.0,4.0,30,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,68.0,2.0,758580,1Q35ej,8.0,6.0,170,1,0,1,...,0,0,0,0,0,0,0,0,1,0
4,32.0,1.0,758580,EAN4J6,5.0,4.0,170,0,0,1,...,0,0,0,0,0,0,0,0,1,0
5,28.0,2.0,758580,8R6pzR,4.0,2.0,170,1,0,1,...,0,0,0,0,0,0,0,0,1,0
6,29.0,2.0,776420,aZJ2XN,6.0,4.0,40,1,0,1,...,0,0,0,0,0,0,0,0,1,0
7,54.0,2.0,776420,Nmpo3J,5.0,3.0,40,1,0,1,...,0,0,0,0,0,0,0,0,1,0
8,28.0,2.0,776420,eVqWar,6.0,4.0,40,0,0,1,...,0,0,0,0,0,0,0,0,1,0
9,37.0,2.0,820850,6ZBD33,8.0,6.0,154,1,1,0,...,0,0,0,0,0,0,0,0,1,0

In [19]:
df_concat.shape

(10741324, 39)

In [20]:
# Check
# post_info_widp = post_info.drop(['idpostulante'], axis = 1)
# post_info_widp.head(10)

### Agrego la columna de probabilidades

In [21]:
#df_concat['sepostulo'] = 1.0

In [22]:
#df_concat.head()

#### Elimino las columnas idaviso e idpostulante

In [23]:
df_concat.drop(['idaviso', 'idpostulante'], 1, inplace = True)

In [24]:
df_concat.head()

,edad,estado,nivel,nombre,nombre_area,sexo,nombre_zona_Buenos Aires (fuera de GBA),nombre_zona_Capital Federal,nombre_zona_Catamarca,nombre_zona_Ciudad de Mendoza,...,tipo_de_trabajo_Por Horas,tipo_de_trabajo_Primer empleo,tipo_de_trabajo_Teletrabajo,tipo_de_trabajo_Temporario,tipo_de_trabajo_Voluntario,nivel_laboral_Gerencia / Alta Gerencia / Dirección,nivel_laboral_Jefe / Supervisor / Responsable,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior
0,42.0,2.0,9.0,7.0,30,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1,31.0,2.0,5.0,3.0,30,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,36.0,2.0,6.0,4.0,30,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,68.0,2.0,8.0,6.0,170,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,32.0,1.0,5.0,4.0,170,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0

### Divido los datasets en 2: test y training

In [25]:
test = df_concat[:100000]
training = df_concat[100000:]

In [26]:
test

,edad,estado,nivel,nombre,nombre_area,sexo,nombre_zona_Buenos Aires (fuera de GBA),nombre_zona_Capital Federal,nombre_zona_Catamarca,nombre_zona_Ciudad de Mendoza,...,tipo_de_trabajo_Por Horas,tipo_de_trabajo_Primer empleo,tipo_de_trabajo_Teletrabajo,tipo_de_trabajo_Temporario,tipo_de_trabajo_Voluntario,nivel_laboral_Gerencia / Alta Gerencia / Dirección,nivel_laboral_Jefe / Supervisor / Responsable,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior
0,42.0,2.0,9.0,7.0,30,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
1,31.0,2.0,5.0,3.0,30,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,36.0,2.0,6.0,4.0,30,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,68.0,2.0,8.0,6.0,170,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
4,32.0,1.0,5.0,4.0,170,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
5,28.0,2.0,4.0,2.0,170,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
6,29.0,2.0,6.0,4.0,40,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
7,54.0,2.0,5.0,3.0,40,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
8,28.0,2.0,6.0,4.0,40,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
9,37.0,2.0,8.0,6.0,154,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,31.0,2.0,4.0,2.0,154,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,38.0,2.0,8.0,6.0,154,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,28.0,2.0,4.0,2.0,154,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
13,45.0,1.0,4.0,3.0,170,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
14,37.0,2.0,5.0,3.0,170,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
15,35.0,0.0,4.0,4.0,170,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
16,42.0,1.0,5.0,4.0,154,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
17,31.0,2.0,6.0,4.0,154,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
18,40.0,2.0,6.0,4.0,154,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
19,38.0,2.0,4.0,2.0,154,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
20,33.0,1.0,4.0,3.0,112,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21,35.0,1.0,5.0,4.0,112,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,34.0,2.0,4.0,2.0,112,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,32.0,1.0,5.0,4.0,26,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,37.0,2.0,7.0,5.0,26,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
25,53.0,2.0,6.0,4.0,26,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
26,NaN,NaN,NaN,NaN,185,-1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
27,42.0,2.0,8.0,6.0,185,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
28,47.0,1.0,5.0,4.0,185,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
29,40.0,2.0,6.0,4.0,112,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,31.0,2.0,6.0,4.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99971,47.0,1.0,7.0,6.0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99972,35.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99973,28.0,2.0,8.0,6.0,170,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99974,42.0,2.0,8.0,6.0,170,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99975,33.0,2.0,8.0,6.0,170,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99976,33.0,2.0,5.0,3.0,32,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99977,32.0,1.0,5.0,4.0,32,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99978,NaN,NaN,NaN,NaN,32,-1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99979,38.0,2.0,6.0,4.0,156,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
99980,37.0,2.0,5.0,3.0,156,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
99981,29.0,0.0,4.0,4.0,156,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
99982,41.0,2.0,6.0,4.0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99983,30.0,2.0,6.0,4.0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99984,35.0,2.0,6.0,4.0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99985,30.0,2.0,6.0,4.0,30,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99986,33.0,2.0,6.0,4.0,30,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99987,33.0,2.0,5.0,3.0,30,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99988,NaN,NaN,NaN,NaN,33,-1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99989,30.0,2.0,4.0,2.0,33,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99990,36.0,2.0,8.0,6.0,33,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99991,31.0,1.0,5.0,4.0,117,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99992,47.0,2.0,6.0,4.0,117,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99993,32.0,2.0,4.0,2.0,117,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99994,41.0,2.0,5.0,3.0,141,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
99995,39.0,2.0,6.0,4.0,141,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
99996,38.0,2.0,6.0,4.0,141,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
99997,40.0,1.0,4.0,3.0,138,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
99998,31.0,1.0,5.0,4.0,138,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
99999,44.0,2.0,4.0,2.0,138,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [27]:
training

,edad,estado,nivel,nombre,nombre_area,sexo,nombre_zona_Buenos Aires (fuera de GBA),nombre_zona_Capital Federal,nombre_zona_Catamarca,nombre_zona_Ciudad de Mendoza,...,tipo_de_trabajo_Por Horas,tipo_de_trabajo_Primer empleo,tipo_de_trabajo_Teletrabajo,tipo_de_trabajo_Temporario,tipo_de_trabajo_Voluntario,nivel_laboral_Gerencia / Alta Gerencia / Dirección,nivel_laboral_Jefe / Supervisor / Responsable,nivel_laboral_Junior,nivel_laboral_Otro,nivel_laboral_Senior / Semi-Senior
100000,49.0,1.0,7.0,6.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100001,49.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100002,58.0,1.0,5.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100003,58.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100004,42.0,1.0,4.0,3.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100005,42.0,2.0,4.0,2.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100006,52.0,1.0,7.0,6.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100007,52.0,2.0,8.0,6.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100008,52.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100009,42.0,1.0,7.0,6.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100010,42.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100011,42.0,2.0,5.0,3.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100012,37.0,1.0,5.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100013,37.0,2.0,4.0,2.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100014,37.0,2.0,3.0,1.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100015,42.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100016,42.0,2.0,7.0,5.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100017,51.0,2.0,3.0,1.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100018,51.0,0.0,4.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100019,42.0,2.0,5.0,3.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100020,42.0,2.0,8.0,6.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100021,42.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100022,51.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100023,57.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100024,47.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100025,36.0,2.0,6.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100026,36.0,1.0,5.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100027,35.0,1.0,5.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100028,33.0,1.0,5.0,4.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100029,33.0,2.0,5.0,3.0,2,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10741294,23.0,2.0,4.0,2.0,145,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741295,20.0,2.0,4.0,2.0,30,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741296,32.0,2.0,5.0,3.0,30,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741297,32.0,2.0,4.0,2.0,30,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741298,42.0,1.0,4.0,3.0,155,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741299,42.0,1.0,5.0,4.0,155,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741300,42.0,2.0,6.0,4.0,155,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741301,42.0,2.0,5.0,3.0,155,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741302,42.0,0.0,4.0,4.0,155,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741303,33.0,2.0,6.0,4.0,187,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741304,33.0,2.0,4.0,2.0,187,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741305,33.0,2.0,6.0,4.0,187,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741306,33.0,2.0,3.0,1.0,187,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741307,37.0,1.0,5.0,4.0,185,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741308,38.0,2.0,6.0,4.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10741309,38.0,2.0,4.0,2.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10741310,28.0,1.0,3.0,2.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741311,28.0,1.0,2.0,1.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741312,19.0,1.0,3.0,2.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741313,44.0,1.0,4.0,3.0,134,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10741314,44.0,2.0,5.0,3.0,134,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
10741315,40.0,2.0,4.0,2.0,123,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741316,19.0,1.0,3.0,2.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741317,24.0,1.0,4.0,3.0,145,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
10741318,24.0,2.0,4.0,2.0,145,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
10741319,18.0,2.0,4.0,2.0,145,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
10741320,25.0,1.0,5.0,4.0,81,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10741321,25.0,2.0,3.0,1.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741322,25.0,0.0,4.0,4.0,145,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10741323,20.0,0.0,2.0,2.0,143,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

### Genero el csv para entrenar

In [28]:
test.to_csv('csvs/test_gnb.csv', index=False)

In [29]:
training.to_csv('csvs/training_gnb.csv', index=False)